import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createProductStore} from '../src/product-store.js';
import {createApp} from '../server.js';
import {createAiAssistant} from '../src/ai.js';
import {creativeScenes,inspectPlan,replacements,recommendCreative,relationshipIds} from '../src/creative.js';
import {equipment,localDate} from '../src/booking.js';
import {addDays} from '../src/planning.js';
import {rankSearch,specLabel} from '../public/creative-client.js';
const tomorrow=()=>addDays(localDate(),1),slot='14:00–16:00';
function store(t){const db=createProductStore(':memory:');t.after(()=>db.close());return db;}
test('十个场景都有真实设备与能力组合，关联图仅返回真实id',()=>{assert.equal(creativeScenes.length,10);for(const scene of creativeScenes){assert.ok(scene.ids.length>=3);assert.ok(scene.ids.every(id=>equipment.some(item=>item.id===id)));}assert.ok(relationshipIds('camera').every(id=>equipment.some(item=>item.id===id)));});
test('准备度只按真实时段计算，冲突、维护、无效设备或日期不会假装就绪',()=>{const plan={date:tomorrow(),slot,equipmentIds:['camera','projector','recorder','gimbal-g1']};const result=inspectPlan(plan,[{date:plan.date,slot,equipmentId:'camera'}]);assert.equal(result.readiness,75);assert.equal(result.available,3);assert.equal(result.items[0].available,false);assert.equal(inspectPlan({...plan,equipmentIds:['drone-a2']},[]).readiness,0);assert.throws(()=>inspectPlan({...plan,equipmentIds:['fake']},[]));assert.throws(()=>inspectPlan({...plan,date:'2026-02-31'},[]));});
test('Smart Replace同用途、真实空闲、排除已选与维护，适配度可解释',()=>{const list=replacements('camera',tomorrow(),slot,[],equipment,['camera-c2']);assert.ok(list.length);assert.ok(list.every(item=>item.capability==='imaging'&&item.id!=='camera-c2'&&item.operationalStatus==='active'));assert.equal(list[0].fit,100);assert.equal(replacements('projector',tomorrow(),slot,[],equipment).length,2);assert.deepEqual(replacements('invalid',tomorrow(),slot,[]),[]);});
test('SQLite seed可重复，不覆盖偏好、不重复账号、设备或收藏',t=>{const db=store(t),user=db.users()[0];db.preferences(user.id,{font:'xlarge',theme:'dark'});db.seed();assert.equal(db.users().length,4);assert.equal(db.workspace(user.id).user.prefs.font,'xlarge');db.favorite(user.id,'camera',true);db.favorite(user.id,'camera',true);assert.deepEqual(db.workspace(user.id).favorites,['camera']);});
test('多账号收藏、方案、历史、导出来源隔离；取消保留历史并可重约',t=>{const db=store(t),[a,b]=db.users();db.favorite(a.id,'camera',true);assert.deepEqual(db.workspace(b.id).favorites,[]);const booking=db.add({userId:a.id,equipmentId:'camera',date:tomorrow(),slot});assert.equal(booking.name,a.name);assert.throws(()=>db.cancel(booking.id,b.id),error=>error.status===403);db.cancel(booking.id,a.id);assert.equal(db.list().length,0);assert.equal(db.workspace(a.id).history[0].status,'cancelled');assert.equal(db.workspace(b.id).history.length,0);db.add({userId:b.id,equipmentId:'camera',date:tomorrow(),slot});assert.equal(db.list().length,1);});
test('SQLite唯一时段继续拒绝重复；预约不伪造真实使用或守约率',t=>{const db=store(t),a=db.users()[0],input={userId:a.id,equipmentId:'camera',date:tomorrow(),slot};db.add(input);assert.throws(()=>db.add(input),error=>error.status===409);const activity=db.workspace(a.id).footprints;assert.equal(activity.explore.value,1);assert.equal(activity.commit.value,1);assert.equal(activity.create.value,0);assert.equal(activity.returnRate,undefined);assert.equal(db.workspace(a.id).achievements.length,1);});
test('方案保存、修改、冲突替换、完成准备与里程碑均真实持久化',t=>{const db=store(t),[a,b]=db.users(),base={name:'采访',sceneId:'interview',date:tomorrow(),slot,equipmentIds:['camera','projector']};let plan=db.savePlan(a.id,base);assert.equal(plan.readiness,100);db.add({userId:b.id,equipmentId:'camera',date:tomorrow(),slot});assert.equal(db.workspace(a.id).plans[0].readiness,50);assert.throws(()=>db.readyPlan(a.id,plan.id),error=>error.status===409);plan=db.savePlan(a.id,{...base,equipmentIds:['camera-c2','projector']},plan.id);db.readyPlan(a.id,plan.id);assert.equal(db.workspace(a.id).plans[0].status,'ready');assert.equal(db.workspace(a.id).footprints.create.value,1);assert.equal(db.workspace(a.id).achievements.filter(item=>item.key==='first-plan').length,1);});
test('本人已经预约的计划设备视为锁定，不能错误推荐替换自己的预约',t=>{const db=store(t),a=db.users()[0],plan=db.savePlan(a.id,{name:'计划',date:tomorrow(),slot,equipmentIds:['camera']});db.add({userId:a.id,equipmentId:'camera',date:tomorrow(),slot});const updated=db.workspace(a.id).plans[0];assert.equal(updated.readiness,100);assert.equal(updated.items[0].secured,true);assert.equal(updated.items[0].reason,'已为你锁定');assert.deepEqual(updated.items[0].alternatives,[]);});
test('方案归属、未知账号、重复昵称与不安全头像拒绝',t=>{const db=store(t),[a,b]=db.users(),plan=db.savePlan(a.id,{name:'计划',date:tomorrow(),slot,equipmentIds:['camera']});assert.throws(()=>db.savePlan(b.id,{...plan,name:'偷改'},plan.id),error=>error.status===404);assert.throws(()=>db.workspace('none'));assert.throws(()=>db.createUser({name:a.name}),error=>error.status===409);assert.throws(()=>db.preferences(a.id,{avatar:'https://tracking.invalid/x.png'}));assert.throws(()=>db.preferences(a.id,{avatar:'data:image/svg+xml;base64,PHN2Zz4='}));assert.throws(()=>db.preferences(a.id,{theme:'unknown'}));});
test('旧JSON迁移先备份且保留id，重开SQLite与重复seed不丢预约',async t=>{const dir=await mkdtemp(join(tmpdir(),'borrow-sql-'));t.after(()=>rm(dir,{recursive:true,force:true}));const legacy=join(dir,'reservations.json'),file=join(dir,'borrow.sqlite'),row={id:'old-identity',name:'蒲嘉洋',equipmentId:'camera',date:tomorrow(),slot,createdAt:new Date().toISOString()};await writeFile(legacy,JSON.stringify([row]));let db=createProductStore(file,{legacyFile:legacy});assert.equal(db.list()[0].id,row.id);assert.deepEqual(JSON.parse(await readFile(legacy+'.pre-sqlite-backup','utf8')),[row]);db.close();db=createProductStore(file,{legacyFile:legacy});assert.equal(db.list().length,1);assert.equal(db.workspace(db.users()[0].id).history.length,1);db.close();});
test('AI创作推荐来自真实catalog、匿名台账，结构化操作结果与冲突一致',async()=>{let sent;const assistant=createAiAssistant({config:{YOSHUB_API_KEY:'mock'},fetchImpl:async(url,{body})=>{sent=JSON.parse(body);return{ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({sceneId:'interview',date:tomorrow(),slot,equipmentIds:['gimbal-g1','microphone-m1','light-f1']})}}]})};}});const result=await assistant.assist({mode:'creative',question:'明天下午采访'},[{equipmentId:'microphone-m1',date:tomorrow(),slot,name:'私密姓名'}]);assert.equal(result.total,3);assert.equal(result.available,2);assert.equal(result.readiness,67);assert.equal(result.items[1].alternatives.length,2);assert.equal(JSON.stringify(sent).includes('私密姓名'),false);assert.equal(sent.max_tokens,3000);assert.equal(result.attempts,1);});
test('AI虚构设备被过滤，全部虚构时按真实场景重配，不放行未知场景',()=>{const result=recommendCreative({sceneId:'vlog',date:tomorrow(),slot,equipmentIds:['made-up']},[]);assert.match(result.notice,/重新匹配/);assert.ok(result.equipmentIds.every(id=>equipment.some(item=>item.id===id)));assert.throws(()=>recommendCreative({sceneId:'invented',date:tomorrow(),slot,equipmentIds:['camera']},[]));});
test('Command Palette联合设备、场景、计划和AI入口，不误匹配原始HTML',()=>{const result=rankSearch('采访',equipment,creativeScenes,[{id:'p',name:'周五采访'}]);assert.ok(result.some(row=>row.type==='equipment'));assert.ok(result.some(row=>row.type==='scene'));assert.ok(result.some(row=>row.type==='plan'));assert.equal(result[0].type,'ai');});
test('HTTP产品路径可操作，私有SQLite/备份/env和后端模块不可访问',async t=>{const db=store(t),app=createApp(db,createAiAssistant({config:{}}));await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>app.close(resolve)));const base='http://127.0.0.1:'+app.address().port,a=db.users()[0];const workspace=await(await fetch(base+'/api/workspace?userId='+a.id)).json();assert.equal(workspace.user.id,a.id);const result=await fetch(base+'/api/plans/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:tomorrow(),slot,equipmentIds:['camera']})});assert.equal(result.status,200);for(const path of ['/product.js','/product.css','/creative.js','/icons.js','/brand.svg'])assert.equal((await fetch(base+path)).status,200);for(const path of ['/.env','/data/borrow-lab.sqlite','/data/reservations.json.pre-sqlite-backup','/src/product-store.js'])assert.equal((await fetch(base+path)).status,404);});

test('视觉参数保留USB、无线频率、视频与焦距的完整单位',()=>{assert.equal(specLabel('USB导出'),'USB');assert.equal(specLabel('2.4GHz无线'),'2.4GHz');assert.equal(specLabel('4K视频'),'4K');assert.equal(specLabel('35mm定焦'),'35mm');});
test('创作推荐截断、空回答与非法结构清晰失败且每次只有一次上游调用',async()=>{
 for(const choice of [{finish_reason:'length',message:{content:'{}'}},{finish_reason:'stop',message:{content:''}},{finish_reason:'stop',message:{content:'null'.padEnd(30)}}]){
  let calls=0;const assistant=createAiAssistant({config:{YOSHUB_API_KEY:'mock'},fetchImpl:async()=>{calls++;return{ok:true,json:async()=>({choices:[choice]})};}});
  await assert.rejects(()=>assistant.assist({mode:'creative',question:'采访'},[]));assert.equal(calls,1);
 }
 assert.throws(()=>recommendCreative(null,[]),error=>error.status===502);
});
