import test from 'node:test';
import assert from 'node:assert/strict';
import {createRouteMemory} from '../public/navigation.js';
import {readAvatar,MAX_AVATAR_BYTES,createPreferenceQueue,accountPreferences} from '../public/profile-client.js';
import {draftSnapshot,saveDraft,readDraft,planOptimizationQuestion,optimizedDraft} from '../public/plan-flow.js';
const catalog=[{id:'camera',name:'相机'},{id:'mic',name:'无线麦'}];
const draft={id:'mine',name:'校园采访',sceneId:'interview',date:'2026-10-09',slot:'14:00–16:00',equipmentIds:['camera']};
test('navigation restores each view scroll and browser back/forward',()=>{const r=createRouteMemory();assert.equal(r.move('equipment',920).position,0);assert.equal(r.move('plans',650).position,0);assert.equal(r.restore(1,430).position,650);assert.equal(r.restore(2,660).position,430);assert.equal(r.move('discover',440).position,920);});
test('same-view actions do not scroll to the top',()=>{const r=createRouteMemory('plans');assert.deepEqual(r.move('plans',780),{view:'plans',index:0,back:null,position:780,changed:false});assert.equal(r.move('plans',780,{top:true}).position,0);});
test('new navigation after back discards forward trail',()=>{const r=createRouteMemory();r.move('equipment',1);r.move('plans',2);r.restore(0,3);r.move('space',1);assert.equal(r.restore(2,0),null);assert.equal(r.state().back,'discover');});
for(const type of ['png','jpeg','webp'])test('avatar accepts decoded '+type,async()=>{const data=`data:image/${type};base64,YQ==`;assert.equal(await readAvatar({type:'image/'+type,size:12},{read:async()=>data,decode:async()=>({width:800,height:600}),encode:()=>data}),data);});
test('avatar rejects unsupported types and oversize before reading',async()=>{const read=()=>{throw Error('must not read');};await assert.rejects(readAvatar({type:'image/svg+xml',size:12},{read}),/PNG/);await assert.rejects(readAvatar({type:'image/png',size:MAX_AVATAR_BYTES+1},{read}),/10MB/);await assert.rejects(readAvatar({type:'image/png',size:0},{read}),/没有内容/);});
test('avatar rejects invalid image decoding or read failure',async()=>{await assert.rejects(readAvatar({type:'image/png',size:12},{read:async()=> 'data:image/png;base64,YQ==',decode:async()=>{throw Error('corrupt');}}),/corrupt/);await assert.rejects(readAvatar({type:'image/png',size:12},{read:async()=>{throw Error('unreadable');}}),/unreadable/);await assert.rejects(readAvatar({type:'image/png',size:12},{read:async()=> 'text'}),/无法打开/);});
test('drafts persist per account without sharing equipment arrays',()=>{const map=new Map(),store={setItem:(k,v)=>map.set(k,v),getItem:k=>map.get(k)};assert.equal(saveDraft(store,'a',draft),true);assert.equal(readDraft(store,'b',catalog),null);const restored=readDraft(store,'a',catalog);assert.deepEqual(restored,draft);restored.equipmentIds.push('mic');assert.equal(draft.equipmentIds.length,1);assert.equal(draftSnapshot(draft).equipmentIds.length,1);});
test('invalid drafts and storage failures are recoverable',()=>{for(const value of ['{broken',JSON.stringify({...draft,equipmentIds:['unknown']}),JSON.stringify({...draft,equipmentIds:['camera','camera']}),JSON.stringify({...draft,slot:'xx'}),JSON.stringify({...draft,date:'2026-02-31'})])assert.equal(readDraft({getItem:()=>value},'a',catalog),null);assert.equal(saveDraft({setItem:()=>{throw Error('quota');}},'a',draft),false);});
test('AI optimization carries real plan and respects input limit',()=>{const question=planOptimizationQuestion({...draft,available:1},catalog);assert.match(question,/2026-10-09 14:00–16:00/);assert.match(question,/相机/);assert.match(question,/1\s*\/\s*1/);assert.ok(question.length<=300);});
test('AI optimization replaces only equipment, preserving name, identity and moment',()=>{const result=optimizedDraft({date:'2099-01-01',name:'invented',equipmentIds:['camera','mic']},draft);assert.deepEqual(result,{...draft,equipmentIds:['camera','mic']});result.equipmentIds.pop();assert.deepEqual(draft.equipmentIds,['camera']);});

import {createAiAssistant} from '../src/ai.js';
import {addDays} from '../src/planning.js';
import {localDate} from '../src/booking.js';

test('explicit plan optimization uses a small context, bounded 1536 token budget and separate deadline',async()=>{let sent;const assistant=createAiAssistant({config:{YOSHUB_API_KEY:'mock'},timeoutMs:2,creativeTimeoutMs:500,fetchImpl:async(url,{signal,body})=>{sent=JSON.parse(body);await new Promise(resolve=>setTimeout(resolve,15));if(signal.aborted)throw signal.reason;return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({keep:['camera'],replace:[],remove:[],reason:'保留当前装备'})}}]})};}});const result=await assistant.assist({mode:'creative',optimization:true,question:'优化已有Vlog方案',plan:{...draft,date:addDays(localDate(),1)}},[]);assert.equal(result.attempts,1);assert.equal(sent.max_tokens,1536);assert.equal(Object.hasOwn(sent,'thinking'),false);assert.equal(Object.hasOwn(sent,'reasoning_effort'),false);});
test('optimization timeout remains finite, with exactly one upstream call',async()=>{let calls=0;const assistant=createAiAssistant({config:{YOSHUB_API_KEY:'mock'},creativeTimeoutMs:5,fetchImpl:async(url,{signal})=>{calls++;await new Promise(resolve=>setTimeout(resolve,15));if(signal.aborted)throw signal.reason;throw Error('unexpected');}});await assert.rejects(assistant.assist({mode:'creative',optimization:true,question:'优化采访',plan:{...draft,date:addDays(localDate(),1)}},[]),/超时/);assert.equal(calls,1);});

test('preference writes preserve account and click order across delayed responses',async()=>{let release,started;const began=new Promise(resolve=>started=resolve),calls=[];const queue=createPreferenceQueue(async(id,value)=>{calls.push({id,value});if(calls.length===1){started();await new Promise(resolve=>release=resolve);}return value;});const first=queue('a',{font:'large'}),second=queue('b',{font:'standard'});await began;assert.equal(calls.length,1);release();await Promise.all([first,second]);assert.deepEqual(calls,[{id:'a',value:{font:'large'}},{id:'b',value:{font:'standard'}}]);});
test('failed preference save does not block subsequent settings',async()=>{let count=0;const queue=createPreferenceQueue(async()=>{if(++count===1)throw Error('offline');return 'saved';});const first=queue('a',{}),second=queue('a',{});await assert.rejects(first,/offline/);assert.equal(await second,'saved');assert.equal(count,2);});

test('an account with no saved preferences resets previous account appearance',()=>{const first={font:'xlarge',theme:'dark',reduceMotion:true};assert.deepEqual(accountPreferences(first),first);assert.deepEqual(accountPreferences({}),{font:'standard',theme:'auto',reduceMotion:false});assert.deepEqual(accountPreferences({font:'invalid',theme:'invalid'}),{font:'standard',theme:'auto',reduceMotion:false});assert.deepEqual(first,{font:'xlarge',theme:'dark',reduceMotion:true});});
