import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
await cp('src/booking.js', 'dist/booking.js');
await cp('src/planning.js', 'dist/planning.js');
await cp('src/catalog.js', 'dist/catalog.js');
await cp('src/creative.js','dist/creative.js');
await cp('src/plan-state.js','dist/plan-state.js');
await cp('src/notifications.js','dist/notifications.js');
await cp('src/occupancy.js','dist/occupancy.js');
const html = await readFile('public/index.html', 'utf8');
await writeFile('dist/index.html', html.replace('<head>', '<head><meta name="storage-mode" content="browser">'));
await writeFile('dist/.nojekyll', '');
console.log('Built static Pages demo in dist; browser-local data only.');
