import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import { mkdirSync,existsSync,readFileSync,copyFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { equipment,validateBooking,BookingError,localDate } from './booking.js';
import { inspectPlan,creativeScenes,replacements } from './creative.js';
import { addDays,freeSlots } from './planning.js';

const avatars=['orbit','prism','tide','dusk','sunrise','moss','iris','silver'];
export function createProductStore(file,{legacyFile}={}){
 if(file!==':memory:')mkdirSync(dirname(file),{recursive:true});
 const db=new DatabaseSync(file);db.exec(`PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,role TEXT NOT NULL,avatar TEXT NOT NULL,prefs TEXT NOT NULL DEFAULT '{}');
 CREATE TABLE IF NOT EXISTS equipment(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),equipment_id TEXT NOT NULL,date TEXT NOT NULL,slot TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',payload TEXT NOT NULL);
 CREATE UNIQUE INDEX IF NOT EXISTS active_slot ON reservations(equipment_id,date,slot) WHERE status='active';
 CREATE TABLE IF NOT EXISTS favorites(user_id TEXT REFERENCES users(id),equipment_id TEXT REFERENCES equipment(id),PRIMARY KEY(user_id,equipment_id));
 CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),payload TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS achievements(user_id TEXT REFERENCES users(id),key TEXT,title TEXT,created_at TEXT,PRIMARY KEY(user_id,key));
 CREATE TABLE IF NOT EXISTS metadata(key TEXT PRIMARY KEY,value TEXT);`);
 const stmt=sql=>db.prepare(sql),parse=row=>JSON.parse(row.payload);
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}
 function requireUser(id){const row=stmt('SELECT * FROM users WHERE id=?').get(id);if(!row)throw new BookingError('请选择一个有效账号。',404);return {...row,prefs:JSON.parse(row.prefs)};}
 function userForName(name){if(typeof name!=='string'||!name.trim()||name.length>30)throw new BookingError('昵称需为1～30个字符。');let row=stmt('SELECT * FROM users WHERE name=?').get(name);if(!row){const id=randomUUID();stmt('INSERT INTO users(id,name,role,avatar) VALUES(?,?,?,?)').run(id,name,'创作者','orbit');row=stmt('SELECT * FROM users WHERE id=?').get(id);}return row;}
 function seed(){for(const item of equipment)stmt('INSERT OR IGNORE INTO equipment VALUES(?,?)').run(item.id,JSON.stringify(item));for(const [name,role,avatar]of [['蒲嘉洋','创作者','orbit'],['创作组同学A','影像探索者','prism'],['创作组同学B','声音记录者','tide'],['游客体验账号','新朋友','dusk']]){if(!stmt('SELECT id FROM users WHERE name=?').get(name))stmt('INSERT INTO users(id,name,role,avatar) VALUES(?,?,?,?)').run(randomUUID(),name,role,avatar);}}
 transaction(seed);
 if(legacyFile&&existsSync(legacyFile)&&!stmt("SELECT value FROM metadata WHERE key='legacy-import'").get()){
  const rows=JSON.parse(readFileSync(legacyFile,'utf8'));if(!Array.isArray(rows))throw new Error('Legacy data invalid; import stopped');
  if(!existsSync(legacyFile+'.pre-sqlite-backup'))copyFileSync(legacyFile,legacyFile+'.pre-sqlite-backup');
  transaction(()=>{for(const row of rows){if(!row.id||!equipment.some(item=>item.id===row.equipmentId))throw new Error('Legacy record invalid; import stopped');const user=userForName(row.name);const payload={...row,userId:user.id};stmt('INSERT OR IGNORE INTO reservations VALUES(?,?,?,?,?,?,?)').run(row.id,user.id,row.equipmentId,row.date,row.slot,'active',JSON.stringify(payload));}stmt("INSERT INTO metadata VALUES('legacy-import',?)").run(String(rows.length));});
 }
 function list(){return stmt("SELECT payload FROM reservations WHERE status='active'").all().map(parse);}
 function unlock(userId,key,title){stmt('INSERT OR IGNORE INTO achievements VALUES(?,?,?,?)').run(userId,key,title,new Date().toISOString());}
 function add(input){return transaction(()=>{const user=input.userId?requireUser(input.userId):userForName(input.name?.trim());const value={...input,name:user.name};const booking={...validateBooking(value,list()),id:randomUUID(),userId:user.id,createdAt:new Date().toISOString()};stmt('INSERT INTO reservations VALUES(?,?,?,?,?,?,?)').run(booking.id,user.id,booking.equipmentId,booking.date,booking.slot,'active',JSON.stringify(booking));const total=stmt('SELECT COUNT(*) n FROM reservations WHERE user_id=?').get(user.id).n;unlock(user.id,'first-booking','创作启程');if(total>=5)unlock(user.id,'five-bookings','五次启程');const categories=new Set(stmt('SELECT payload FROM reservations WHERE user_id=?').all(user.id).map(parse).map(row=>equipment.find(item=>item.id===row.equipmentId)?.category));if(categories.size>=5)unlock(user.id,'five-categories','跨界探索者');return booking;});}
 function cancel(id,userId){const row=stmt("SELECT * FROM reservations WHERE id=? AND status='active'").get(id);if(!row)throw new BookingError('预约不存在或已取消。',404);if(!userId)throw new BookingError('请选择预约所属账号。',403);if(row.user_id!==userId)throw new BookingError('只能取消自己的预约。',403);const payload={...parse(row),status:'cancelled',cancelledAt:new Date().toISOString()};stmt("UPDATE reservations SET status='cancelled',payload=? WHERE id=?").run(JSON.stringify(payload),id);}
 function users(){return stmt('SELECT * FROM users').all().map(row=>({...row,prefs:JSON.parse(row.prefs)}));}
 function createUser(input){const name=typeof input.name==='string'?input.name.trim():'';if(!name||name.length>30)throw new BookingError('昵称需为1～30个字符。');if(stmt('SELECT id FROM users WHERE name=?').get(name))throw new BookingError('这个昵称已经存在。',409);return requireUser(userForName(name).id);}
 function preferences(id,input){const user=requireUser(id);const prefs={...user.prefs};if(input.font) {if(!['standard','large','xlarge'].includes(input.font))throw new BookingError('字号设置无效。');prefs.font=input.font;}if(input.theme){if(!['auto','light','dark'].includes(input.theme))throw new BookingError('主题设置无效。');prefs.theme=input.theme;}if(typeof input.reduceMotion==='boolean')prefs.reduceMotion=input.reduceMotion;let avatar=user.avatar;if(input.avatar){if(!avatars.includes(input.avatar)&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(input.avatar))throw new BookingError('头像需为PNG/JPEG/WebP图片。');if(input.avatar.length>500000)throw new BookingError('头像请小于350KB。');avatar=input.avatar;}stmt('UPDATE users SET prefs=?,avatar=? WHERE id=?').run(JSON.stringify(prefs),avatar,id);return requireUser(id);}
 function favorite(id,equipmentId,enabled){requireUser(id);if(!equipment.some(item=>item.id===equipmentId))throw new BookingError('设备不存在。',404);stmt(enabled?'INSERT OR IGNORE INTO favorites VALUES(?,?)':'DELETE FROM favorites WHERE user_id=? AND equipment_id=?').run(id,equipmentId);return workspace(id);}
 function savePlan(id,input,planId){requireUser(id);const scene=creativeScenes.find(row=>row.id===input.sceneId);const name=typeof input.name==='string'?input.name.trim():scene?.name;if(!name||name.length>60)throw new BookingError('请给计划取一个不超过60字的名字。');const value={name,sceneId:scene?.id||'custom',date:input.date,slot:input.slot,equipmentIds:input.equipmentIds};inspectPlan(value,list());if(planId){const old=stmt('SELECT * FROM plans WHERE id=? AND user_id=?').get(planId,id);if(!old)throw new BookingError('计划不存在。',404);}const plan={...value,id:planId||randomUUID(),userId:id,status:'draft',updatedAt:new Date().toISOString()};stmt('INSERT INTO plans VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').run(plan.id,id,JSON.stringify(plan));unlock(id,'first-plan','灵感成形');return inspectPlan(plan,list());}
 function readyPlan(id,planId){requireUser(id);const row=stmt('SELECT * FROM plans WHERE id=? AND user_id=?').get(planId,id);if(!row)throw new BookingError('计划不存在。',404);const plan=inspectPlan(parse(row),list());if(plan.readiness!==100)throw new BookingError('先解决设备冲突，再完成准备。',409);const value={...parse(row),status:'ready',readyAt:new Date().toISOString()};stmt('UPDATE plans SET payload=? WHERE id=?').run(JSON.stringify(value),planId);unlock(id,'ready-plan','万事就绪');return value;}
 function workspace(id){const user=requireUser(id);const history=stmt('SELECT payload,status FROM reservations WHERE user_id=? ORDER BY date DESC').all(id).map(row=>({...parse(row),status:row.status}));const plans=stmt('SELECT payload FROM plans WHERE user_id=?').all(id).map(parse);const achievements=stmt('SELECT key,title,created_at FROM achievements WHERE user_id=?').all(id);const favs=stmt('SELECT equipment_id FROM favorites WHERE user_id=?').all(id).map(row=>row.equipment_id);const categories=new Set(history.map(row=>equipment.find(item=>item.id===row.equipmentId)?.category).filter(Boolean));const upcoming=history.filter(row=>row.status==='active'&&row.date>=localDate());const notifications=upcoming.slice(0,6).map(row=>({id:row.id,title:row.date===localDate()?'你的预约就在今天':'下一次创作已安排',text:`${equipment.find(item=>item.id===row.equipmentId)?.name} · ${row.date} · ${row.slot}`,view:'reservations'}));for(const plan of plans){if(plan.date>=localDate()&&inspectPlan(plan,list()).readiness<100)notifications.push({id:plan.id,title:'计划里有设备需要调整',text:plan.name,view:'plans'});}
  return {user,history,plans:plans.map(plan=>inspectPlan(plan,list(),equipment,{allowPast:true})),favorites:favs,achievements,notifications,footprints:{explore:{value:categories.size,target:10,label:'探索类别'},create:{value:plans.filter(plan=>plan.status==='ready').length,target:3,label:'准备计划'},commit:{value:upcoming.length,target:3,label:'已安排预约'}},avatars};}
 return {list,add,cancel,users,createUser,preferences,favorite,savePlan,readyPlan,workspace,seed,close:()=>db.close(),replace:(id,date,slot)=>replacements(id,date,slot,list()),heatmap:(date=localDate())=>Array.from({length:7},(_,i)=>{const day=addDays(date,i);return {date:day,slots:freeSlots(list(),day,'camera'),free:equipment.reduce((n,item)=>n+freeSlots(list(),day,item.id).length,0),capacity:equipment.filter(item=>item.operationalStatus==='active').length*3};})};
}
